### ISSUE TITLE
Missing pcre-config and pcre.h

### ISSUE THREAD

**Issue by versat** [orbitcowboy/afl_cppcheck#1]
In Ubuntu 14.04 i get the following error message:
```
make: pcre-config: Command not found
build/cppcheck.cpp:50:18: fatal error: pcre.h: No such file or directory
 #include <pcre.h>
                  ^
compilation terminated.
make: *** [build/cppcheck.o] Error 1
```
`sudo apt-get install libpcre3-dev` fixes the problem.
Maybe this should be added to the documentation/comments in the script.

**Comment by orbitcowboy** [comment]
Thanks!
Fixed as of https://github.com/orbitcowboy/afl_cppcheck/commit/09524f7d310c17a6d0540af6228fb879faa04140
